In [1]:
import numpy as np

### Comparisions and masking

In [2]:
a = np.array([1, 3, 4])
b = np.array([2, 2, 7])

In [3]:
c = a < b
print(c)
print(c.all())  # were all True
print(c.any())  # was some comparision True
print(a[c])  # values on a less than b
print("True values: ", np.sum(c))  # total of less values

[ True False  True]
False
True
[1 4]
True values:  2


In [4]:
print(a > 0)

[ True  True  True]


In [5]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/csmastersUH/data_analysis_with_python_2020/master/kumpula-weather-2017.csv")['Air temperature (degC)'].values

In [6]:
df

array([  0.6,  -3.9,  -6.5, -12.8, -17.8, -17.8,  -3.8,  -0.5,   0.5,
         1.7,  -1.6,  -2.8,   1.1,   0.8,  -2.8,  -4.2,  -3.5,   1.1,
         1.6,  -0.6,  -1.8,   1. ,   0.1,  -2.2,  -3.8,   1.9,   1.6,
         0.8,   0.6,   1. ,   0.2,  -0.6,  -0.8,  -0.2,   0.4,  -2.5,
        -7.3, -12.1,  -8.8, -10.1,  -8.3,  -5.4,  -2.7,   1.5,   4.4,
         0. ,   0.5,   1.5,   1.9,   2.2,   0.4,  -2.5,  -4.6,  -0.7,
        -5.3,  -5.6,  -2. ,  -2.3,   2.1,   1.5,   1.5,   0.9,  -1.8,
        -4.2,  -4.2,  -2.9,   0.2,   1.2,   1.4,   2.2,  -0.9,   0.6,
         0.6,   3.8,   3.4,   2. ,   1.6,   0.6,   0.2,   1.6,   2.3,
         2.5,   0.5,   1.9,   4.8,   6.6,   2.4,   0.4,  -0.4,   0.2,
         1.5,   4.3,   3. ,   3.8,   3.3,   4.7,   4.1,   3.3,   3.7,
         6. ,   4.3,   1.8,   1.2,  -0.5,  -1.4,  -1.7,   0.6,   0.3,
         1.2,   2.5,   5.7,   3.1,   2.9,   3.6,   2.8,   3.2,   4.4,
         4.1,   2.3,   2.2,   7.6,   9.4,   9.2,   6.7,  10.1,  11.1,
         6.1,   4.4,

In [7]:
print("Number of days with temperature below zero: ", np.sum(df < 0))

Number of days with temperature below zero:  49


In [8]:
np.sum( (0 < df) & (df < 10))  # Temperature greater than 0 and less than 10

np.int64(185)

In [9]:
c = df > 0
print(c[:10])  # print only the first ten elements
print(df[c])  # Select only the positive temperatures

[ True False False False False False False False  True  True]
[ 0.6  0.5  1.7  1.1  0.8  1.1  1.6  1.   0.1  1.9  1.6  0.8  0.6  1.
  0.2  0.4  1.5  4.4  0.5  1.5  1.9  2.2  0.4  2.1  1.5  1.5  0.9  0.2
  1.2  1.4  2.2  0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5
  0.5  1.9  4.8  6.6  2.4  0.4  0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1
  3.3  3.7  6.   4.3  1.8  1.2  0.6  0.3  1.2  2.5  5.7  3.1  2.9  3.6
  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1  6.1  4.4
  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9 14.7 14.6
 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.   9.9 10.4
 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3 16.9 17.8
 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1 16.4 14.5
 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7 18.  15.4
 15.  13.7 14.6 15.8 15.6 16.9 15.7 16.1 17.2 19.  19.1 17.8 18.3 17.8
 18.9 17.5 18.2 16.6 17.1 16.  15.2 17.2 18.3 18.7 18.1 19.6 17.4 16.1
 16.4 17.6 19.  

In [10]:
# Asign new values using masking
df[~c] = 0
print(df)

[ 0.6  0.   0.   0.   0.   0.   0.   0.   0.5  1.7  0.   0.   1.1  0.8
  0.   0.   0.   1.1  1.6  0.   0.   1.   0.1  0.   0.   1.9  1.6  0.8
  0.6  1.   0.2  0.   0.   0.   0.4  0.   0.   0.   0.   0.   0.   0.
  0.   1.5  4.4  0.   0.5  1.5  1.9  2.2  0.4  0.   0.   0.   0.   0.
  0.   0.   2.1  1.5  1.5  0.9  0.   0.   0.   0.   0.2  1.2  1.4  2.2
  0.   0.6  0.6  3.8  3.4  2.   1.6  0.6  0.2  1.6  2.3  2.5  0.5  1.9
  4.8  6.6  2.4  0.4  0.   0.2  1.5  4.3  3.   3.8  3.3  4.7  4.1  3.3
  3.7  6.   4.3  1.8  1.2  0.   0.   0.   0.6  0.3  1.2  2.5  5.7  3.1
  2.9  3.6  2.8  3.2  4.4  4.1  2.3  2.2  7.6  9.4  9.2  6.7 10.1 11.1
  6.1  4.4  1.5  1.5  2.9  5.1  7.5  9.8  9.   7.3  9.4 11.2 16.1 16.9
 14.7 14.6 13.3 12.4 14.1 14.1  9.6 13.2 14.1  9.6 10.8  6.5  6.2 10.
  9.9 10.4 14.5 16.4 12.3 14.  16.3 16.8 12.6 12.6 14.8 15.1 18.4 19.3
 16.9 17.8 12.7 12.4 12.2 10.8 12.9 14.  13.5 13.7 15.3 16.3 17.2 14.1
 16.4 14.5 14.1 14.  11.5 14.7 16.1 17.4 18.  16.8 16.8 14.7 15.3 16.7
 18.  15.

### E3.1 (column comparison)
Write function column_comparison that gets a two dimensional array as parameter. The function should return a new array containing those rows from the input that have the value in the second column larger than in the second last column. You may assume that the input contains at least two columns. Don't use loops, but instead vectorized operations. Try out your function in the main function.



In [11]:
def column_comparison(arr: np.ndarray):
    mask = arr[:, 1] > arr[:, -2] 
    return arr[mask]

In [12]:
a = np.array(
[[8, 9, 3, 8, 8],
 [0, 5, 3, 9, 9],
 [5, 7, 6, 0, 4],
 [7, 8, 1, 6, 2],
 [2, 1, 3, 5, 8]]
)
print(column_comparison(a))

[[8 9 3 8 8]
 [5 7 6 0 4]
 [7 8 1 6 2]]


### E3.2 (fitst half second half)
Write function first_half_second_half that gets a two dimensional array of shape (n,2*m) as a parameter. The input array has 2*m columns. The output from the function should be a matrix with those rows from the input that have the sum of the first m elements larger than the sum of the last m elements on the row. Your solution should call the np.sum function or the corresponding method exactly twice.

In [13]:
def first_half_second_half(arr: np.ndarray):
    _, m = arr.shape
    m = int(m / 2)
    return [row for row in arr if np.sum(row[:m]) > np.sum(row[m:])]

In [14]:
a = np.array([[1, 3, 4, 2],
              [2, 2, 1, 2]])
print( first_half_second_half(a) )

[array([2, 2, 1, 2])]


In [15]:
_, m = a.shape
m = m // 2
mask = np.sum(a[:, :m], axis=1) > np.sum(a[:, m: ], axis=1)
print(a[mask])

[[2 2 1 2]]


In [16]:
def info(a: np.ndarray): 
    print("Dimension:", a.ndim)
    print("Shape [n x m]:", a.shape)
    print("Size [n * m]:", a.size)
    print("dtype:", a.dtype)
    for row in a: 
        print(row)
    print()

### Fancy indexing

In [17]:
rng = np.random.default_rng(0)

In [18]:
a = rng.integers(0, 20, 20)
a

array([17, 12, 10,  5,  6,  0,  1,  0,  3, 16, 12, 18, 10, 12, 19, 14, 12,
       10, 11, 18])

In [19]:
idx = [0, 2, 5, 13]
print(a[idx])

[17 10  0 12]


In [20]:
a[idx] = -100
a

array([-100,   12, -100,    5,    6, -100,    1,    0,    3,   16,   12,
         18,   10, -100,   19,   14,   12,   10,   11,   18])

In [21]:
b = np.arange(16).reshape(4, 4)
info(b)
row = np.array([0, 2])
col = np.array([1, 3])
print(b[row, col])  # row: 0, col: 1 = 1; row: 2, col: 3 = 2

Dimension: 2
Shape [n x m]: (4, 4)
Size [n * m]: 16
dtype: int64
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]

[ 1 11]


In [22]:
row = np.array([0, -1])
col = np.array([0, -1])
print(b[row, col])

[ 0 15]


### Sorting arrays

In [23]:
a=np.array([2,1,4,3,5])
print(a)
print("sorted", np.sort(a))

[2 1 4 3 5]
sorted [1 2 3 4 5]


In [24]:
a.sort()
print(a)

[1 2 3 4 5]


In [25]:
b = rng.integers(0,10, (4,4))
print(b)

[[2 8 6 0]
 [3 8 5 0]
 [7 7 8 1]
 [0 8 0 5]]


In [26]:
np.sort(b, axis=0) ## Sort by columns

array([[0, 7, 0, 0],
       [2, 8, 5, 0],
       [3, 8, 6, 1],
       [7, 8, 8, 5]])

In [27]:
np.sort(b, axis=1)  # Sort by rows

array([[0, 2, 6, 8],
       [0, 3, 5, 8],
       [1, 7, 7, 8],
       [0, 0, 5, 8]])

In [28]:
# np.argsort return the indices of the sorted elements. 
a = np.array([23,12,47,35,59])
print("Array a:", a)
idx = np.argsort(a)
print("Indices:", idx)

Array a: [23 12 47 35 59]
Indices: [1 0 3 2 4]


### E3.3 (most frecuent first)

Write function most_frequent_first that gets a two dimensional array and an index c of a column as parameters. The function should then return the array whose rows are sorted based on column c, in the following way. Rows are ordered so that those rows with the most frequent element in column c come first, then come the rows with the second most frequent element in column c, and so on. Therefore, the values outside column c don't affect the ordering in any way.


In [29]:
def most_frequent_first(a: np.ndarray, c: int):
    pass

In [30]:
a = np.array(
 [[5, 0, 3, 3, 7, 9, 3, 5, 2, 4],
 [7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
 [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
 [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
 [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
 [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
 [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
 [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
 [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
 [5, 9, 3, 0, 5, 0, 1, 2, 4, 2]])



### Matrix Operations

In [31]:
a = rng.integers(0, 10, (3, 2))
b = rng.integers(0, 10, (2, 4))
info(a)
info(b)

Dimension: 2
Shape [n x m]: (3, 2)
Size [n * m]: 6
dtype: int64
[0 2]
[4 4]
[4 0]

Dimension: 2
Shape [n x m]: (2, 4)
Size [n * m]: 8
dtype: int64
[0 1 0 6]
[5 6 2 6]



In [32]:
c = np.matmul(a, b)
info(c)

Dimension: 2
Shape [n x m]: (3, 4)
Size [n * m]: 12
dtype: int64
[10 12  4 12]
[20 28  8 48]
[ 0  4  0 24]



In [33]:
print(a @ b)

[[10 12  4 12]
 [20 28  8 48]
 [ 0  4  0 24]]


In [34]:
print(a @ a.T)

[[ 4  8  0]
 [ 8 32 16]
 [ 0 16 16]]


In [35]:
print(a.T @ a)

[[32 16]
 [16 20]]


## E3.4 (matrix power)

Repeat the functionality of the NumPy function numpy.linalg.matrix_power, which raises a square matrix of shape (m,m) to the nth power. Here the multiplication is the matrix multiplication. Square matrix a raised to power n is therefore a @ a @ ... @ a where a is repeated n times. When n is zero then $a^{0}$ is equal to np.eye(m).

Write function matrix_power that gets as first argument a square matrix a and as second argument a non-negative integer n. The function should return the matrix a multiplied by itself n-1 times. Use Python's reduce function and a generator expression.

Extend the matrix_power function. For negative powers, we define $a^{-1}$ to be equal to the multiplicative inverse of a. You can use NumPy's function numpy.linalg.inv for this. And you may assume that the input matrix is invertible.



In [52]:
from functools import reduce

In [53]:
help(reduce)

Help on built-in function reduce in module _functools:

reduce(...)
    reduce(function, iterable[, initial]) -> value

    Apply a function of two arguments cumulatively to the items of a sequence
    or iterable, from left to right, so as to reduce the iterable to a single
    value.  For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
    ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
    of the iterable in the calculation, and serves as a default when the
    iterable is empty.



In [61]:
def matrix_power(a: np.ndarray, n: int): 
    m = len(a)
    if n == 0:
        return np.eye(m)
    elif n == -1: 
        return np.linalg.inv(a)
    
    return reduce(lambda X, Y: X @ Y, [a] * (n - 1), a)

In [69]:
arr = np.array([[2.5, 0], 
                [0, 2.5]])
info(arr)

Dimension: 2
Shape [n x m]: (2, 2)
Size [n * m]: 4
dtype: float64
[2.5 0. ]
[0.  2.5]



In [70]:
print(matrix_power(arr, 0))

[[1. 0.]
 [0. 1.]]


In [71]:
print(matrix_power(arr, -1))

[[0.4 0. ]
 [0.  0.4]]


In [72]:
inv = matrix_power(arr, -1)
print(arr @ inv)

[[1. 0.]
 [0. 1.]]


In [73]:
print(matrix_power(arr, 3))

[[15.625  0.   ]
 [ 0.    15.625]]


## E3.5(correlation)

In [85]:
import scipy.stats as stats

In [ ]:
def load():
    import pandas as pd
    return pd.read_csv("data/iris.csv").drop('species', axis=1).values

def lengths(data: np.ndarray):
    pearson_result = stats.pearsonr(data[:, 0], data[:, 2])
    return pearson_result[0]

def correlations(data: np.ndarray):
    return np.corrcoef(data.T)

In [86]:
data = load()
data[:5, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [87]:
help(stats.pearsonr)

Help on function pearsonr in module scipy.stats._stats_py:

pearsonr(x, y, *, alternative='two-sided', method=None, axis=0)
    Pearson correlation coefficient and p-value for testing non-correlation.

    The Pearson correlation coefficient [1]_ measures the linear relationship
    between two datasets. Like other correlation
    coefficients, this one varies between -1 and +1 with 0 implying no
    correlation. Correlations of -1 or +1 imply an exact linear relationship.
    Positive correlations imply that as x increases, so does y. Negative
    correlations imply that as x increases, y decreases.

    This function also performs a test of the null hypothesis that the
    distributions underlying the samples are uncorrelated and normally
    distributed. (See Kowalski [3]_
    for a discussion of the effects of non-normality of the input on the
    distribution of the correlation coefficient.)
    The p-value roughly indicates the probability of an uncorrelated system
    producing 

In [91]:
pearson_result = stats.pearsonr(data[:, 0], data[:, 2]) 
print(pearson_result)

PearsonRResult(statistic=np.float64(0.8717537758865831), pvalue=np.float64(1.038667419449872e-47))


In [92]:
help(np.corrcoef)

Help on _ArrayFunctionDispatcher in module numpy:

corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)
    Return Pearson product-moment correlation coefficients.

    Please refer to the documentation for `cov` for more detail.  The
    relationship between the correlation coefficient matrix, `R`, and the
    covariance matrix, `C`, is

    .. math:: R_{ij} = \frac{ C_{ij} } { \sqrt{ C_{ii} C_{jj} } }

    The values of `R` are between -1 and 1, inclusive.

    Parameters
    ----------
    x : array_like
        A 1-D or 2-D array containing multiple variables and observations.
        Each row of `x` represents a variable, and each column a single
        observation of all those variables. Also see `rowvar` below.
    y : array_like, optional
        An additional set of variables and observations. `y` has the same
        shape as `x`.
    rowvar : bool, optional
        If `rowvar` is True (default), then each row represents a
        variable, with 

In [94]:
corr = np.corrcoef(data.T)
print(corr)

[[ 1.         -0.11756978  0.87175378  0.81794113]
 [-0.11756978  1.         -0.4284401  -0.36612593]
 [ 0.87175378 -0.4284401   1.          0.96286543]
 [ 0.81794113 -0.36612593  0.96286543  1.        ]]
