In [1]:
import numpy as np

### Creation of arrays

In [11]:
a = np.array([1,2 , 3])  # One dimensional array

In [12]:
a.shape

(3,)

In [13]:
type(a)

numpy.ndarray

In [15]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
b.shape

(2, 3)

In [20]:
print(b[0])
print(b[1])

[1 2 3]
[4 5 6]


In [30]:
b_reshaped = b.reshape(-1,2)
print(b_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
zeros = np.zeros(shape=(3, 4), dtype=int)
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [35]:
ones = np.ones(shape=(2, 3), dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]]


In [39]:
sevens = np.full(shape=(3, 3), fill_value=7)
print(sevens)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
print(sevens.flatten())

[7 7 7 7 7 7 7 7 7]


In [41]:
empty = np.empty((3, 3))
print(empty)

[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [44]:
I3 = np.eye(M=3, N=3, dtype=int)
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [58]:
arange = np.arange(start=0, stop=10, step=1)  # arange is used for integer ranges
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
linspace = np.linspace(start=0, stop=np.pi, num=100)  # Evenly spaced range with 5 elements
print(linspace)

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

### Arrays with random elements

In [70]:
arr = np.random.random((3, 3))  # Elements are uniformly distributed from half-open interval [0.0,1.0)
print(arr)

[[0.68104077 0.03850448 0.58533288]
 [0.586103   0.34495787 0.01109426]
 [0.90571646 0.80415189 0.52431422]]


In [75]:
arrnormal = np.random.normal(0, 1, (4, 4))  # Elements are normally distributed with mean 0 and stdev 1
print(arrnormal)

[[-2.21169832  0.66895837  0.90112569  0.75402738]
 [ 0.03515088  1.39348375 -1.68750841 -0.78117545]
 [-0.0745599  -0.40538169 -1.09406577  1.00259701]
 [-1.11481194 -0.52280121 -1.02967167 -1.33092355]]


In [83]:
arrint = np.random.randint(low=-10, high=10, size=(3, 3))
print(arrint)

[[ -5  -1   9]
 [ -1 -10  -9]
 [ -2  -4  -2]]


### Random Generator

In [84]:
rng = np.random.default_rng(seed=42)

In [86]:
print(rng.integers(0, 100, 10))

[52 97 73 76 71 78 51 12 83 45]


In [88]:
print(rng.integers(-100, 100, (5, 5)))

[[ 94 -11  78  35  55]
 [ 51 -62 -28  -7  -1]
 [-92   9 -70  48  36]
 [ 84  48 -27  93 -18]
 [-35  81 -26 -85  -7]]


In [90]:
print(rng.normal(1, 2, (3, 3)))  # 3x3 array normally distributed with mean 1 and stdev 2

[[ 1.23337162  1.43737719  2.74285756]
 [ 1.4471911   2.35782713  1.13515814]
 [ 1.5782388   2.26257645 -1.91431164]]


In [92]:
print(rng.standard_normal(size=(3, 3)))  # 3x3 array normaly distributed

[[ 0.16275307  0.58622233  0.71122658]
 [ 0.79334724 -0.34872507 -0.46235179]
 [ 0.85797588 -0.19130432 -1.27568632]]


### Array types and atributes

In [116]:
def info(a: np.ndarray): 
    print("Dimension:", a.ndim)
    print("Shape [n x m]:", a.shape)
    print("Size [n * m]:", a.size)
    print("dtype:", a.dtype)
    for row in a: 
        print(row)

In [117]:
info(b)

Dimension: 2
Shape [n x m]: (2, 3)
Size [n * m]: 6
dtype: int64
[1 2 3]
[4 5 6]


In [118]:
c = np.array([b, b])
info(c)

Dimension: 3
Shape [n x m]: (2, 2, 3)
Size [n * m]: 12
dtype: int64
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [119]:
row = np.array([1, 2, 3, 4])
info(row)

Dimension: 1
Shape [n x m]: (4,)
Size [n * m]: 4
dtype: int64
1
2
3
4


In [120]:
col = row.reshape(-1, 1)
info(col)

Dimension: 2
Shape [n x m]: (4, 1)
Size [n * m]: 4
dtype: int64
[1]
[2]
[3]
[4]


In [121]:
info(col.reshape(1, -1))

Dimension: 2
Shape [n x m]: (1, 4)
Size [n * m]: 4
dtype: int64
[1 2 3 4]


### Indexing, slicing and reshaping

In [127]:
t = np.arange(1, 10).reshape(3, 3)
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[1 2 3]
[4 5 6]
[7 8 9]


In [131]:
print(t[1, 0])
print(t[-1, 1])

4
8


In [136]:
print(t[:, 0].reshape(-1, 1))

[[1]
 [4]
 [7]]


In [139]:
print(t[0:3, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [142]:
print(t[:, 1:].reshape(-1, 2))

[[2 3]
 [5 6]
 [8 9]]


In [143]:
t[-1, -1] = 10
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[1 2 3]
[4 5 6]
[ 7  8 10]


In [144]:
t[0, :] = 0
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[0 0 0]
[4 5 6]
[ 7  8 10]


In [124]:
randten = rng.integers(0, 10, size=(3,3))
info(randten)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[0 2 8]
[0 8 2]
[9 2 4]


In [145]:
d = np.arange(4)  # 1d array
drow = d.reshape(1, -1)  # Row vector
dcol = d.reshape(-1, 1)  # Col vector

info(d)
info(drow)
info(dcol)

Dimension: 1
Shape [n x m]: (4,)
Size [n * m]: 4
dtype: int64
0
1
2
3
Dimension: 2
Shape [n x m]: (1, 4)
Size [n * m]: 4
dtype: int64
[0 1 2 3]
Dimension: 2
Shape [n x m]: (4, 1)
Size [n * m]: 4
dtype: int64
[0]
[1]
[2]
[3]


In [146]:
dd = d.reshape(2, 2)  # 2x2 matrix
info(dd)

Dimension: 2
Shape [n x m]: (2, 2)
Size [n * m]: 4
dtype: int64
[0 1]
[2 3]


## E2.1

Write two functions, get_rows and get_columns, that get a two dimensional array as parameter. They should return the list of rows and columns of the array, respectively. The rows and columns should be one dimensional arrays. 

In [ ]:
def get_rows(arr: np.ndarray):
    return 

def get_cols(arr: np.ndarray): 
    pass

In [147]:
a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])