In [1]:
import numpy as np

In [7]:
def info(arr: np.ndarray):
    print(arr)
    print(f"dim: {arr.ndim}\nshape: {arr.shape}\nsize: {arr.size}\ndtype: {arr.dtype}\n")

In [9]:
# Aconcatenations, splitting

a = np.arange(2)
b = np.arange(2, 5)
info(a)
info(b)

[0 1]
dim: 1
shape: (2,)
size: 2
dtype: int64

[2 3 4]
dim: 1
shape: (3,)
size: 3
dtype: int64



In [10]:
c = np.concat([a, b])
info(c)

[0 1 2 3 4]
dim: 1
shape: (5,)
size: 5
dtype: int64



In [20]:
arr = np.arange(1, 5).reshape(2, 2)
info(arr)

info(np.concat((arr, arr)))

info(np.concat((arr, arr), axis=1))

[[1 2]
 [3 4]]
dim: 2
shape: (2, 2)
size: 4
dtype: int64

[[1 2]
 [3 4]
 [1 2]
 [3 4]]
dim: 2
shape: (4, 2)
size: 8
dtype: int64

[[1 2 1 2]
 [3 4 3 4]]
dim: 2
shape: (2, 4)
size: 8
dtype: int64



In [ ]:
print(b, "\n")
print(np.stack((b, b), axis=0), "\n")
print(np.stack((b, b), axis=1), "\n")


[2 3 4] 

[[2 3 4]
 [2 3 4]] 

[[2 2]
 [3 3]
 [4 4]] 



In [35]:
d = np.arange(12).reshape(6,2)
print("d:")
print(d, "\n")
d1, d2 = np.split(d, 2)
print("d1:")
print(d1, "\n")
print("d2:")
print(d2, "\n")

d:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

d1:
[[0 1]
 [2 3]
 [4 5]] 

d2:
[[ 6  7]
 [ 8  9]
 [10 11]] 



In [38]:
d = np.arange(12).reshape(2,6)
print("d:")
print(d, "\n")
parts = np.split(ary=d, indices_or_sections=(2, 3, 5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)

d:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 

part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


In [39]:
def get_row_vectors(arr):
    return [row.reshape(1, -1) for row in arr]

def get_column_vectors(arr):
    return [col.reshape(-1, 1) for col in arr.T]

In [40]:
np.random.seed(0)
a = np.random.randint(0,10, (4,4))
print("a:\n", a)
print("Row vectors:\n", get_row_vectors(a))
print("Column vectors:\n", get_column_vectors(a))

a:
 [[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]
Row vectors:
 [array([[5, 0, 3, 3]], dtype=int32), array([[7, 9, 3, 5]], dtype=int32), array([[2, 4, 7, 6]], dtype=int32), array([[8, 8, 1, 6]], dtype=int32)]
Column vectors:
 [array([[5],
       [7],
       [2],
       [8]], dtype=int32), array([[0],
       [9],
       [4],
       [8]], dtype=int32), array([[3],
       [3],
       [7],
       [1]], dtype=int32), array([[3],
       [5],
       [6],
       [6]], dtype=int32)]


In [49]:
np.eye(M=3, N=3, k=-1) + np.eye(M=3, N=3, k=1)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [ ]:
n = 3