In [1]:
import numpy as np

### Creation of arrays

In [2]:
a = np.array([1,2 , 3])  # One dimensional array

In [3]:
a.shape

(3,)

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
b.shape

(2, 3)

In [7]:
print(b[0])
print(b[1])

[1 2 3]
[4 5 6]


In [8]:
b_reshaped = b.reshape(-1,2)
print(b_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
zeros = np.zeros(shape=(3, 4), dtype=int)
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
ones = np.ones(shape=(2, 3), dtype=int)
print(ones)

[[1 1 1]
 [1 1 1]]


In [11]:
sevens = np.full(shape=(3, 3), fill_value=7)
print(sevens)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [12]:
print(sevens.flatten())

[7 7 7 7 7 7 7 7 7]


In [13]:
empty = np.empty((3, 3))
print(empty)

[[3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323]]


In [14]:
I3 = np.eye(M=3, N=3, dtype=int)
print(I3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [15]:
arange = np.arange(start=0, stop=10, step=1)  # arange is used for integer ranges
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
linspace = np.linspace(start=0, stop=np.pi, num=100)  # Evenly spaced range with 5 elements
print(linspace)

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

### Arrays with random elements

In [17]:
arr = np.random.random((3, 3))  # Elements are uniformly distributed from half-open interval [0.0,1.0)
print(arr)

[[0.30244652 0.04713748 0.71304608]
 [0.80761412 0.77139572 0.06624629]
 [0.31910788 0.22954109 0.47004171]]


In [18]:
arrnormal = np.random.normal(0, 1, (4, 4))  # Elements are normally distributed with mean 0 and stdev 1
print(arrnormal)

[[-0.80086857 -2.45204939 -1.4929159   0.67160328]
 [ 1.48876438  0.01100542 -0.01598256  0.29720761]
 [ 1.7211603   1.69128965 -1.50352764  1.24165373]
 [-1.43259966 -0.52934013  0.43568225  1.34158142]]


In [19]:
arrint = np.random.randint(low=-10, high=10, size=(3, 3))
print(arrint)

[[  1 -10   5]
 [  9   5   6]
 [  8  -8  -4]]


### Random Generator

In [20]:
rng = np.random.default_rng(seed=42)

In [21]:
print(rng.integers(0, 100, 10))

[ 8 77 65 43 43 85  8 69 20  9]


In [22]:
print(rng.integers(-100, 100, (5, 5)))

[[  5  95  47  52  43]
 [ 57   2 -75  67 -10]
 [  0 -26 -64  85  56]
 [ 28 -20  64   9 -12]
 [-10 -55 -82  10  77]]


In [23]:
print(rng.normal(1, 2, (3, 3)))  # 3x3 array normally distributed with mean 1 and stdev 2

[[ 2.7569006   0.90014818  0.63027527]
 [-0.36185909  3.44508268  0.69094104]
 [ 0.14334436  0.2957329   2.06461837]]


In [24]:
print(rng.standard_normal(size=(3, 3)))  # 3x3 array normaly distributed

[[ 0.36544406  0.41273261  0.430821  ]
 [ 2.1416476  -0.40641502 -0.51224273]
 [-0.81377273  0.61597942  1.12897229]]


### Array types and atributes

In [25]:
def info(a: np.ndarray): 
    print("Dimension:", a.ndim)
    print("Shape [n x m]:", a.shape)
    print("Size [n * m]:", a.size)
    print("dtype:", a.dtype)
    for row in a: 
        print(row)
    print()

In [26]:
info(b)

Dimension: 2
Shape [n x m]: (2, 3)
Size [n * m]: 6
dtype: int64
[1 2 3]
[4 5 6]



In [27]:
c = np.array([b, b])
info(c)

Dimension: 3
Shape [n x m]: (2, 2, 3)
Size [n * m]: 12
dtype: int64
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]



In [28]:
row = np.array([1, 2, 3, 4])
info(row)

Dimension: 1
Shape [n x m]: (4,)
Size [n * m]: 4
dtype: int64
1
2
3
4



In [29]:
col = row.reshape(-1, 1)
info(col)

Dimension: 2
Shape [n x m]: (4, 1)
Size [n * m]: 4
dtype: int64
[1]
[2]
[3]
[4]



In [30]:
info(col.reshape(1, -1))

Dimension: 2
Shape [n x m]: (1, 4)
Size [n * m]: 4
dtype: int64
[1 2 3 4]



### Indexing, slicing and reshaping

In [31]:
t = np.arange(1, 10).reshape(3, 3)
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[1 2 3]
[4 5 6]
[7 8 9]



In [32]:
print(t[1, 0])
print(t[-1, 1])

4
8


In [33]:
print(t[:, 0].reshape(-1, 1))

[[1]
 [4]
 [7]]


In [34]:
print(t[0:3, :])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(t[:, 1:].reshape(-1, 2))

[[2 3]
 [5 6]
 [8 9]]


In [36]:
t[-1, -1] = 10
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[1 2 3]
[4 5 6]
[ 7  8 10]



In [37]:
t[0, :] = 0
info(t)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[0 0 0]
[4 5 6]
[ 7  8 10]



In [38]:
randten = rng.integers(0, 10, size=(3,3))
info(randten)

Dimension: 2
Shape [n x m]: (3, 3)
Size [n * m]: 9
dtype: int64
[0 4 1]
[6 4 3]
[2 5 6]



In [39]:
d = np.arange(4)  # 1d array
drow = d.reshape(1, -1)  # Row vector
dcol = d.reshape(-1, 1)  # Col vector

info(d)
info(drow)
info(dcol)

Dimension: 1
Shape [n x m]: (4,)
Size [n * m]: 4
dtype: int64
0
1
2
3

Dimension: 2
Shape [n x m]: (1, 4)
Size [n * m]: 4
dtype: int64
[0 1 2 3]

Dimension: 2
Shape [n x m]: (4, 1)
Size [n * m]: 4
dtype: int64
[0]
[1]
[2]
[3]



In [40]:
dd = d.reshape(2, 2)  # 2x2 matrix
info(dd)

Dimension: 2
Shape [n x m]: (2, 2)
Size [n * m]: 4
dtype: int64
[0 1]
[2 3]



## E2.1

Write two functions, get_rows and get_columns, that get a two dimensional array as parameter. They should return the list of rows and columns of the array, respectively. The rows and columns should be one dimensional arrays. 

In [41]:
def get_rows(arr: np.ndarray):
    return [row for row in arr]

def get_columns(arr: np.ndarray): 
    return [col for col in arr.T]

In [42]:
a = np.array([[5, 0, 3, 3],
 [7, 9, 3, 5],
 [2, 4, 7, 6],
 [8, 8, 1, 6]])

In [43]:
get_rows(a)

[array([5, 0, 3, 3]),
 array([7, 9, 3, 5]),
 array([2, 4, 7, 6]),
 array([8, 8, 1, 6])]

In [44]:
get_columns(a)

[array([5, 7, 2, 8]),
 array([0, 9, 4, 8]),
 array([3, 3, 7, 1]),
 array([3, 5, 6, 6])]

### Array concatenation, splitting and stacking

In [45]:
a = np.arange(2)
b = np.arange(2, 5)

print(a.shape, b.shape)

print(np.concatenate((a, b)))  # a + b: error

(2,) (3,)
[0 1 2 3 4]


In [46]:

c = np.arange(1, 5).reshape(2, 2)
print(c, c.shape, sep="\n\n")

[[1 2]
 [3 4]]

(2, 2)


In [47]:
print(np.concatenate((c, c)))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [48]:
print(np.concatenate((c, c), axis=1))

[[1 2 1 2]
 [3 4 3 4]]


In [49]:
info(a.reshape(1, -1))
print(np.concatenate( (c,a.reshape(1,2)) ), "\n")
print(np.concatenate( (c, a.reshape(2, 1)), axis=1))

Dimension: 2
Shape [n x m]: (1, 2)
Size [n * m]: 2
dtype: int64
[0 1]

[[1 2]
 [3 4]
 [0 1]] 

[[1 2 0]
 [3 4 1]]


In [50]:
info(b)
bstack_row = np.stack((b, b))
info(bstack_row)
bstack_col = np.stack((b, b), axis=1)
info(bstack_col)

Dimension: 1
Shape [n x m]: (3,)
Size [n * m]: 3
dtype: int64
2
3
4

Dimension: 2
Shape [n x m]: (2, 3)
Size [n * m]: 6
dtype: int64
[2 3 4]
[2 3 4]

Dimension: 2
Shape [n x m]: (3, 2)
Size [n * m]: 6
dtype: int64
[2 2]
[3 3]
[4 4]



In [51]:
# Column stack
a = np.arange(9).reshape(3, 3)
print(a, "\n")
lst = [row for row in a]
b = np.column_stack(lst)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [52]:
d = np.arange(12).reshape(6, 2)
info(d)

d1, d2 = np.split(d, 2, axis=0)
info(d1)
info(d2)

Dimension: 2
Shape [n x m]: (6, 2)
Size [n * m]: 12
dtype: int64
[0 1]
[2 3]
[4 5]
[6 7]
[8 9]
[10 11]

Dimension: 2
Shape [n x m]: (3, 2)
Size [n * m]: 6
dtype: int64
[0 1]
[2 3]
[4 5]

Dimension: 2
Shape [n x m]: (3, 2)
Size [n * m]: 6
dtype: int64
[6 7]
[8 9]
[10 11]



In [53]:
info(d.reshape(2, 6))
parts = np.split(d.reshape(2, 6), (2, 3, 5), axis=1)
for i, p in enumerate(parts):
    print("part %i:" % i)
    print(p)


Dimension: 2
Shape [n x m]: (2, 6)
Size [n * m]: 12
dtype: int64
[0 1 2 3 4 5]
[ 6  7  8  9 10 11]

part 0:
[[0 1]
 [6 7]]
part 1:
[[2]
 [8]]
part 2:
[[ 3  4]
 [ 9 10]]
part 3:
[[ 5]
 [11]]


## E2.12 (row and column vectors)

Create function get_row_vectors that returns a list of rows from the input array of shape (n,m), but this time the rows must have shape (1,m). Similarly, create function get_columns_vectors that returns a list of columns (each having shape (n,1)) of the input matrix .

In [ ]:
def get_row_vectors(arr: np.ndarray):
    return [row for row in arr]

def get_column_vectors(arr: np.ndarray): 
    return [col.reshape(-1, 1) for col in arr.T]

In [73]:
a = np.array([[5, 0, 3], [3, 7, 9]])
info(a)

print(get_row_vectors(a))
print(get_column_vectors(a))

Dimension: 2
Shape [n x m]: (2, 3)
Size [n * m]: 6
dtype: int64
[5 0 3]
[3 7 9]

[array([5, 0, 3]), array([3, 7, 9])]
[array([[5],
       [3]]), array([[0],
       [7]]), array([[3],
       [9]])]


### Fast computations using universal functions