In [1]:
import numpy as np


In [8]:
def randomization(n): 
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """    
    return np.random.rand(n,1)

In [10]:
print(randomization(3))

[[0.13347649 0.15885887 0.15047399]]


# Matrix properties and operations

In [15]:
x = np.array([3, 5])
print(x)
print(x.shape)
y = np.array([[3, 5, 1], [1, 2, 3]])
print(y)
print(y.shape)

[3 5]
(2,)
[[3 5 1]
 [1 2 3]]
(2, 3)


In [14]:
z = y.transpose()
print(z)
print(z.shape)

[[3 1]
 [5 2]
 [1 3]]
(3, 2)


In [17]:
a = z + 3
print(a)

[[6 4]
 [8 5]
 [4 6]]


In [19]:
b = np.matmul(y, z)
print(b)

[[35 16]
 [16 14]]


In [23]:
x_exp = np.exp(x)
print(x_exp)
x_sine = np.sin(x)
print(x_sine)
x_tanh = np.tanh(x)
print(x_tanh)

[ 20.08553692 148.4131591 ]
[ 0.14112001 -0.95892427]
[0.99505475 0.9999092 ]


In [24]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.rand(h, w)
    B = np.random.rand(h, w)
    s = A + B
    return A, B, s

In [30]:
print(operations(3, 3))

[[0.67183354 0.61974172 0.99087456]
 [0.41331307 1.09851342 0.56890078]
 [0.9439376  0.8536446  0.26275236]]


# Max, Min and Norm

In [39]:
x = np.array([4, -123,12, 312,312,31])
print(x)

[   4 -123   12  312  312   31]


In [41]:
min = x.min()
print('min', min)
max = np.max(x)
print('max', max)

min -123
max 312


In [48]:
random_matrix = np.random.random([4, 4])
print(random_matrix)

[[0.61835241 0.07914704 0.21934997 0.16405419]
 [0.49671195 0.36722086 0.89513602 0.40022469]
 [0.02992155 0.58620654 0.17023111 0.14156336]
 [0.15917747 0.46171509 0.75633171 0.38622033]]


In [51]:
x_norm = np.linalg.norm(x)
print('x_norm', x_norm)

x_norm 459.27987110257726


In [52]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    Z = A + B
    Z_norm = np.linalg.norm(Z)
    return Z_norm

In [62]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    dot_product = np.matmul(weights.transpose(), inputs)
    out = np.tanh(dot_product)
    return out


In [63]:
input_test = np.random.rand(2, 1)
weight_test = np.random.rand(2, 1)
print('input\n', input_test)
print('weight\n', weight_test)

input
 [[0.26935886]
 [0.17635272]]
weight
 [[0.60170367]
 [0.14160658]]


In [65]:
print(neural_network(input_test, weight_test))

[[0.18489565]]


In [66]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print(x * y)
print(x / y)

[ 2  6 12]
[0.5        0.66666667 0.75      ]
